[workspace]
members = ["crates/website", "crates/scraper", "crates/secrets"]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true

[[workspace.metadata.leptos]]
name = "footical-website"
bin-package = "footical-website"
lib-package = "footical-website"
site-root = "target/site"
site-pkg-dir = "pkg"
tailwind-input-file = "crates/website/style/input.css"
site-addr = "0.0.0.0:3000"
reload-port = 3001
bin-features = ["ssr"]
lib-features = ["hydrate"]
