app = "footical-website"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  LEPTOS_SITE_ADDR = "0.0.0.0:3000"
  LEPTOS_SITE_ROOT = "/app/site"
  SCRAPE_HOUR = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  count = 1