[[workspace.members]]
name = "footical-app"
bin-package = "footical-app"
lib-package = "footical-app"
site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "crates/app/style/input.css"
tailwind-input-file = "crates/app/style/input.css"
tailwind-config-file = "tailwind.config.js"
site-addr = "0.0.0.0:3000"
reload-port = 3001
bin-features = ["ssr"]
lib-features = ["hydrate"]
