[package]
name = "footical-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "footical-app"
path = "src/main.rs"

[dependencies]
leptos = { version = "0.7", features = ["csr"] }
leptos_router = { version = "0.7" }
gloo-net = { version = "0.6", features = ["http"] }
gloo-timers = "0.3"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Clipboard", "Navigator", "Window"] }
chrono = { version = "0.4", features = ["wasmbind"] }
